name: Build Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
<<<<<<< HEAD
          activate-environment: my-env
          environment-file: environment.yml
=======
          activate-environment: ci
          environment-file: environment.yml
>>>>>>> 8fdbf27 (changes)

      - name: Install dependencies
        run: conda env update --name my-env --file env.yml --prune

      - name: Run flake8 test
        run: flake8

      - name: Run nonstandardcode.py
        run: python nonstandardcode.py

