name: CI-Multi-Jobs

on:
  push:
    branches:
      - main
      - python/iss#8/package
  workflow_dispatch:

jobs:

  without-checkout-job:
    name: Without Checkout
    runs-on: 'ubuntu-latest'
    steps:
      - name: Install tree & run
        run: |
          sudo apt-get install -y tree
          tree .