name: Build Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: my-env
          environment-file: env.yml

      - name: Install dependencies
        run: conda env update --name my-env --file env.yml --prune

      - name: Run flake8 test
        run: flake8

      - name: Run nonstandardcode.py
        run: python nonstandardcode.py

name : package

on:
  push:
    branches:
      - main
      - python/iss#8/package

jobs:
  without-checkout-job:
    name: without
    runs: 'Ubutu-latest'
    steps:
      - name: Install tree & run
      - run: sudo apt-get install -y tree
              tree .

