name: Python Packaging Workflow

on:
  push:
    branches:
      - main
      - python/iss#8/package

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install tree CLI tool
        run: sudo apt-get install tree -y

      - name: Display directory tree before building
        run: tree

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Display directory tree after building
        run: tree

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: python-package-artifacts
          path: dist/

  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: python-package-artifacts

      - name: Install package
        run: |
          pip install dist/*.whl

      - name: Setup Conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: my-env
          environment-file: env.yml
          auto-activate-base: false

      - name: Run nonstandardcode.py
        run: python nonstandardcode.py
